export const FRASES_DO_DIA: string[] = [
  "Disciplina é fazer o que precisa ser feito, mesmo sem vontade.",
  "Todo grande resultado começou com um dia comum, bem trabalhado.",
  "Você não precisa de motivação todos os dias, precisa de rotina.",
  "O profissional que você quer ser começa no cliente de hoje.",
  "Constância vence talento quando o talento não tem constância.",
  "Um bom dia de trabalho não depende do humor, depende da decisão.",
  "Faça bem o pequeno, e o grande virá até você.",
  "Ninguém nasce disciplinado, todo mundo treina isso todo dia.",
  "O hábito é mais forte que a inspiração.",
  "Comece antes de estar pronto — a prontidão vem fazendo.",
  "Cuide de cada cliente como se fosse o único do dia.",
  "Um corte bem feito fala mais alto do que qualquer propaganda.",
  "Quem escuta o cliente entende o que ele nem sabia pedir.",
  "O detalhe é o que separa o bom do inesquecível.",
  "Atenção é a forma mais simples de respeito.",
  "Trate o primeiro cliente do dia com a energia do último.",
  "Sorrir custa pouco e vale muito no seu trabalho.",
  "O cliente não lembra só do corte, lembra de como foi tratado.",
  "Gentileza no atendimento não tem custo, tem retorno.",
  "Cada cadeira que você atende é uma chance de fidelizar alguém.",
  "Você não é do tamanho dos seus problemas, é do tamanho da sua reação.",
  "Toda dificuldade tem prazo — sua entrega, não.",
  "Quem já superou um dia difícil sabe que consegue superar outro.",
  "Não é sobre nunca cair, é sobre levantar mais rápido.",
  "Força não é não sentir, é seguir sentindo.",
  "O obstáculo de hoje é o preparo pra amanhã.",
  "Resiliência se constrói um dia difícil de cada vez.",
  "Você já passou por coisa pior — e chegou até aqui.",
  "Cansaço passa, desistência fica. Escolha o que vai carregar.",
  "O que te derruba também pode te fortalecer, depende de você.",
  "Onde está sua atenção, está o seu resultado.",
  "Foco é dizer não pra cem coisas boas por uma coisa certa.",
  "Estar presente vale mais do que estar ocupado.",
  "A mente dispersa trabalha o dobro pela metade do resultado.",
  "Um passo de cada vez, mas sempre o próximo.",
  "Distração é ladra de tempo — e tempo não volta.",
  "Quem foca no essencial, sobra energia pro resto.",
  "Presença é o presente que você dá pra quem está na sua frente.",
  "Menos ruído, mais atenção no que importa.",
  "Concentre-se no cliente da cadeira, não no relógio.",
  "Gratidão transforma o pouco em suficiente.",
  "Agradeça pelo dia que você tem, não só pelo que falta.",
  "Quem é grato pelo pequeno recebe o grande com mais leveza.",
  "Antes de reclamar do que falta, olhe pro que já tem.",
  "Cada cliente que confia em você é motivo de gratidão.",
  "Gratidão não espera tudo perfeito pra aparecer.",
  "Valorize quem te ajudou a chegar até aqui.",
  "Um \"obrigado\" sincero muda o clima do dia.",
  "Gratidão é o antídoto pra reclamação.",
  "Reconheça o progresso, mesmo o pequeno.",
  "Humildade é saber que sempre dá pra aprender mais.",
  "Quem se acha pronto, para de evoluir.",
  "O erro ensina mais que o acerto, se você deixar.",
  "Escutar crítica com calma é sinal de maturidade.",
  "Ninguém domina tudo — e tá tudo bem.",
  "Aprender com quem tem mais experiência acelera seu caminho.",
  "Humildade abre portas que o orgulho fecha.",
  "O melhor profissional é o que continua estudando.",
  "Reconhecer que errou é o primeiro passo pra acertar.",
  "Aprenda todo dia um pouco, mesmo que pareça pouco.",
  "Paciência é força disfarçada de calma.",
  "Nem tudo que é bom acontece rápido.",
  "Respire antes de reagir — o resultado agradece.",
  "O cliente difícil de hoje pode virar o mais fiel de amanhã.",
  "Paciência com o processo é o que constrói o resultado.",
  "Correr com raiva cansa mais do que andar com calma.",
  "Dar tempo ao tempo também é trabalhar.",
  "Quem tem paciência, tem estratégia.",
  "Calma não é fraqueza, é controle.",
  "Espera bem vivida também é produtiva.",
  "Coragem não é ausência de medo, é agir apesar dele.",
  "Quem espera o momento perfeito, nunca começa.",
  "A ação, mesmo imperfeita, vale mais que a intenção parada.",
  "Dar o primeiro passo já é metade do caminho andado.",
  "Feito é melhor que perfeito.",
  "Enfrentar o difícil hoje evita o pior amanhã.",
  "Coragem se treina em pequenas decisões diárias.",
  "Quem arrisca aprende, quem não arrisca só imagina.",
  "O medo diminui quando você anda na direção dele.",
  "Ser corajoso é continuar mesmo tremendo por dentro.",
  "O simples bem feito vence o complicado mal executado.",
  "Nem tudo precisa ser difícil pra valer a pena.",
  "Simplicidade é clareza em movimento.",
  "Menos é mais, quando o menos é bem cuidado.",
  "Complicar é fácil, simplificar exige inteligência.",
  "As melhores soluções costumam ser as mais simples.",
  "Um gesto simples pode marcar o dia de alguém.",
  "Simplifique sua rotina pra sobrar espaço pro que importa.",
  "O básico bem feito já coloca você à frente da maioria.",
  "Simplicidade também é sinal de domínio.",
  "Persistir é continuar mesmo quando ninguém está aplaudindo.",
  "Quem desiste no meio nunca sabe o quanto faltava.",
  "A persistência transforma tentativa em resultado.",
  "Cada \"não\" te aproxima de um \"sim\".",
  "Persistência é fé em ação.",
  "Continue, mesmo devagar — parar é que atrasa de verdade.",
  "O sucesso, de longe, parece sorte; de perto, é insistência.",
  "Quem constrói devagar constrói mais forte.",
  "Insistir com inteligência é diferente de insistir por teimosia.",
  "A persistência de hoje é o resultado de amanhã.",
  "Hoje é o único dia que você realmente tem nas mãos.",
  "Não adianta viver de ontem nem esperar amanhã pra agir.",
  "O tempo que passa não negocia volta.",
  "Faça hoje o que só amanhã vai agradecer.",
  "Cada dia é uma nova chance de fazer melhor.",
  "Não deixe o hoje de lado esperando um momento ideal.",
  "Use bem as horas que você tem — elas não se repetem.",
  "O tempo investido em qualidade nunca é tempo perdido.",
  "Comece o dia decidindo como quer terminá-lo.",
  "Hoje bem vivido é ontem bem lembrado.",
  "Crescer dói um pouco — é assim que fica maior.",
  "Você não é a mesma pessoa de um ano atrás, e tá certo.",
  "Todo desconforto de crescimento tem um propósito.",
  "Evoluir é normal, estagnar é que exige esforço.",
  "Quem não se desafia, não se descobre.",
  "O crescimento acontece fora da zona de conforto.",
  "Seja um pouco melhor hoje do que foi ontem.",
  "Crescer é processo, não evento.",
  "Você está mais perto do que imagina.",
  "Investir em você mesmo é o investimento que nunca perde valor.",
  "Você escolhe como reage, mesmo quando não escolhe o que acontece.",
  "Atitude é a única coisa 100% sob seu controle.",
  "Reclamar gasta energia que resolver poderia usar.",
  "Encare o problema, não fuja dele.",
  "A diferença entre dois profissionais iguais é a atitude.",
  "Um bom dia começa com uma boa decisão, não com sorte.",
  "Você pode controlar seu esforço, não o resultado — foque no esforço.",
  "Atitude positiva não ignora o problema, ela enfrenta com leveza.",
  "Escolha a versão de você que constrói, não que reclama.",
  "A forma como você começa o dia contamina o resto dele.",
  "Trabalho bem feito não precisa de aplauso pra valer a pena.",
  "Orgulho do seu ofício aparece nos detalhes.",
  "Fazer certo mesmo quando ninguém está vendo é caráter.",
  "Cada corte é uma assinatura do seu trabalho.",
  "Excelência é hábito, não acidente.",
  "Quem ama o que faz, faz diferente.",
  "Capricho no trabalho é respeito com quem confia em você.",
  "Seu nome está em cada serviço que você entrega.",
  "Fazer bem feito hoje é propaganda pra amanhã.",
  "O padrão que você aceita é o padrão que você entrega.",
  "Respeito começa em como você trata quem parece não importar.",
  "Gentileza é gratuita e tem alto retorno.",
  "Trate todo mundo como gostaria de ser tratado na cadeira.",
  "Um bom dia para o próximo também é um bom dia pra você.",
  "Respeitar o tempo do outro é uma forma de cuidado.",
  "A educação é o cartão de visita que ninguém esquece.",
  "Ser gentil não é ser fraco, é ser forte com controle.",
  "O respeito que você planta, um dia colhe de volta.",
  "Escutar com atenção também é um gesto de respeito.",
  "Mudar de direção não é fracasso, é inteligência.",
  "O que te trouxe até aqui pode não te levar mais longe.",
  "Toda mudança boa começa desconfortável.",
  "Adaptar-se é sobreviver com inteligência.",
  "Quem teme mudar, se acomoda no que já não serve.",
  "A vida recompensa quem se atualiza.",
  "Mudar de ideia com informação nova é maturidade.",
  "O novo assusta antes de ensinar.",
  "Evoluir exige soltar o que já não cabe mais em você.",
  "Propósito transforma trabalho em missão.",
  "Saber o \"porquê\" torna o \"como\" mais leve.",
  "Trabalhar com propósito cansa menos e rende mais.",
  "Encontre sentido no que você faz, não só no que recebe por isso.",
  "Seu trabalho pode mudar o dia de alguém — lembre disso.",
  "Propósito é o combustível que motivação sozinha não dá conta de segurar.",
  "Faça pelo motivo certo, e o resultado certo vem atrás.",
  "Quem sabe pra onde vai, caminha com mais firmeza.",
  "Confiança se constrói com pequenas provas diárias.",
  "Você não precisa ter certeza de tudo pra começar.",
  "Confiar em você mesmo é a base pra confiarem em você.",
  "A dúvida é normal, mas não pode ser quem decide por você.",
  "Preparo gera confiança, confiança gera resultado.",
  "Errar não destrói a confiança, insistir sem aprender é que destrói.",
  "Acredite no seu processo mesmo quando o resultado ainda não apareceu.",
  "Confiança tranquila vale mais que confiança barulhenta.",
  "Consistência é o que separa o amador do profissional.",
  "Fazer certo uma vez é sorte, fazer certo sempre é competência.",
  "O resultado consistente vem de decisões repetidas, não de um dia excelente.",
  "Não é sobre ser perfeito, é sobre ser constante.",
  "A rotina bem feita é o segredo por trás do talento visível.",
  "Consistência não é emocionante, mas é o que funciona.",
  "Cada dia consistente é um tijolo na construção do seu nome.",
  "Aparecer todo dia, mesmo nos dias ruins, é o que constrói reputação.",
  "Autoconhecimento é a ferramenta mais afiada que você pode ter.",
  "Conhecer seus limites é o primeiro passo pra superá-los.",
  "Quem se conhece, se cobra com justiça, não com exagero.",
  "Pare, de vez em quando, pra perguntar como você está de verdade.",
  "Entender seus gatilhos evita que eles te controlem.",
  "Você é seu maior projeto — cuide dele com atenção.",
  "Autocrítica saudável constrói, autocrítica excessiva destrói.",
  "Conhecer-se é o começo de toda mudança real.",
  "Lidere a si mesmo antes de querer liderar qualquer coisa.",
  "A cobrança mais importante é a que você faz com você mesmo.",
  "Disciplina com você mesmo é liberdade no futuro.",
  "Seja o tipo de profissional que você mesmo admiraria.",
  "Ninguém motiva por você o tempo todo — construa sua própria constância.",
  "A responsabilidade pelo seu resultado começa e termina em você.",
  "Liderar-se é decidir bem mesmo quando ninguém está cobrando.",
  "O caminho do outro não é o seu caminho — e não precisa ser.",
  "Comparar-se sem parar rouba a alegria do seu próprio progresso.",
  "Cada um tem seu tempo de florescer.",
  "Olhe pro seu ontem pra medir seu hoje, não pro caminho alheio.",
  "Seu ritmo é válido, mesmo que pareça mais lento que o dos outros.",
  "A corrida de verdade é contra quem você foi ontem.",
  "Admire sem se anular — inspire-se sem se comparar.",
  "Errar faz parte de quem está tentando de verdade.",
  "O erro só é derrota se você não aprender nada com ele.",
  "Recomeçar não é fraqueza, é coragem em forma de ação.",
  "Ninguém acerta sempre — quem acerta sempre é quem parou de tentar coisas novas.",
  "Cada recomeço carrega a experiência do que já passou.",
  "Um erro corrigido vale mais que dez acertos escondidos.",
  "Levante, ajuste a rota, continue.",
  "O fracasso de hoje pode ser o ensaio do sucesso de amanhã.",
  "Equilíbrio é saber quando parar tanto quanto saber quando agir.",
  "Trabalhar bem inclui descansar bem.",
  "Cuidar de você também faz parte de cuidar do seu trabalho.",
  "Nem tudo precisa ser feito com pressa, nem tudo pode esperar — equilibre.",
  "Corpo e mente cansados não entregam o seu melhor.",
  "Descansar não é perder tempo, é investir em qualidade.",
  "Equilíbrio é decidir o que merece sua energia hoje.",
  "Celebre a pequena vitória — ela também é vitória.",
  "Todo avanço, mesmo pequeno, merece ser reconhecido.",
  "Não espere o resultado gigante pra se sentir orgulhoso.",
  "Comemore o progresso, não só o destino final.",
  "Pequenas conquistas somadas viram grandes resultados.",
  "Reconheça seu esforço, mesmo quando o resultado ainda não veio inteiro.",
  "Cada cliente satisfeito é uma pequena vitória que conta.",
  "Dê valor ao caminho, não só à chegada.",
  "O que você pratica hoje, se torna sua habilidade de amanhã.",
  "Cuidado com os detalhes: eles contam a história do seu profissionalismo.",
  "Nenhum cliente esquece quem o tratou bem num dia ruim.",
  "A excelência é feita de pequenas escolhas repetidas.",
  "Quem cultiva boas escolhas, colhe bons resultados.",
  "Trabalhar com alegria contagia quem está ao seu redor.",
  "A rotina só vira monotonia se você deixar de dar sentido a ela.",
  "Seu esforço de hoje é invisível até virar resultado amanhã.",
  "Ser bom no que faz é treino, não sorte.",
  "O profissional que aprende sempre nunca fica pra trás.",
  "Cuide da sua reputação como cuida do seu corte: com capricho.",
  "Quem se compromete com a qualidade, não precisa prometer nada além dela.",
  "O respeito no atendimento constrói clientes fiéis, não só clientes de um dia.",
  "A calma no trato transforma qualquer atendimento difícil.",
  "Seja a razão pela qual alguém teve um dia melhor.",
  "Trabalhar direito, mesmo sem ninguém olhando, é integridade.",
  "A confiança do cliente se conquista atendimento após atendimento.",
  "Cada detalhe que você cuida é um motivo a mais pra ele voltar.",
  "O seu melhor de hoje já é suficiente — amanhã você melhora de novo.",
  "Ser pontual é uma forma silenciosa de respeito.",
  "Quem cuida da própria evolução, nunca para de crescer.",
  "Escute mais do que fala, principalmente no início do atendimento.",
  "Um ambiente de trabalho leve rende resultados mais pesados.",
  "Compartilhar o que você sabe fortalece toda a equipe.",
  "Trabalho em equipe multiplica o que o esforço individual só soma.",
  "Ajudar um colega não diminui você, engrandece o time todo.",
  "Reconhecer o mérito do outro não tira o seu brilho.",
  "Bom ambiente de trabalho começa com boas atitudes individuais.",
  "Um time que se apoia entrega mais que a soma das partes.",
  "A cooperação constrói mais rápido do que a competição interna.",
  "Celebrar a conquista do colega também é celebrar a sua.",
  "O sucesso do time reflete no sucesso de cada um.",
  "Todo especialista já foi iniciante alguém dia.",
  "Não compare seu capítulo um com o capítulo dez de outra pessoa.",
  "O caminho difícil de hoje forma o profissional forte de amanhã.",
  "Você não precisa ser o melhor, precisa ser melhor que ontem.",
  "Dedicação não aparece de uma vez, ela se acumula.",
  "O talento abre a porta, a disciplina mantém você lá dentro.",
  "Ninguém vê as horas de treino, só o resultado final.",
  "Sua trajetória é única — pare de correr atrás da linha de chegada de outro.",
  "Toda jornada longa começou com um primeiro dia incerto.",
  "O progresso silencioso também é progresso de verdade.",
  "Aceitar ajuda não diminui sua capacidade, mostra sua inteligência.",
  "Pedir orientação é sinal de quem quer crescer rápido e certo.",
  "Ninguém chega longe completamente sozinho.",
  "Compartilhar dúvidas é mais rápido do que insistir sozinho no erro.",
  "Boas perguntas valem tanto quanto boas respostas.",
  "Aprender com quem já passou pelo caminho economiza tempo e dor.",
  "A troca de experiência encurta a curva de aprendizado.",
  "Estar aberto a conselhos é abrir espaço pra crescer mais rápido.",
  "Foco no cliente de hoje é o marketing mais eficiente que existe.",
  "Um atendimento excepcional vale mais que qualquer anúncio pago.",
  "O boca a boca começa numa cadeira bem atendida.",
  "Cada cliente satisfeito é um vendedor gratuito do seu trabalho.",
  "A primeira impressão dura, capriche nela.",
  "Um detalhe de cuidado pode transformar um cliente ocasional em fiel.",
  "O jeito como você recebe alguém já diz muito sobre você.",
  "Fidelizar é mais barato — e mais gratificante — que conquistar do zero.",
  "Supere a expectativa, não só a entregue.",
  "O cliente sente quando o atendimento vem de verdade.",
  "Foco no que você pode controlar, solte o que não pode.",
  "Preocupação sem ação só rouba energia do presente.",
  "Ansiedade sobre o amanhã não resolve o hoje.",
  "Respire, organize, execute — nessa ordem.",
  "Um passo bem dado vale mais que dez passos apressados.",
  "Organize sua mente antes de organizar sua agenda.",
  "Clareza sobre prioridades evita o caos do dia a dia.",
  "Planejar bem economiza o dobro de esforço na execução.",
  "Uma rotina organizada sobra tempo pro que realmente importa.",
  "Menos improviso, mais intenção nas suas escolhas do dia.",
  "O sucesso raramente é individual — reconheça quem te ajudou.",
  "Ser grato com quem te ensinou é sinal de caráter.",
  "Valorizar quem investiu em você é retribuir com respeito.",
  "Ninguém constrói uma carreira sozinho, mesmo trabalhando sozinho.",
  "Reconheça as mãos que ajudaram a construir o que você é hoje.",
  "A humildade de agradecer abre espaço pra receber ainda mais.",
  "Uma palavra de reconhecimento vale mais do que parece.",
  "Toda conquista carrega, em algum lugar, a ajuda de alguém.",
  "Motivação vem e vai, comprometimento permanece.",
  "Não espere se sentir motivado pra fazer o que precisa ser feito.",
  "Comprometimento é fazer o combinado, mesmo sem vontade.",
  "A palavra empenhada vale tanto quanto o trabalho entregue.",
  "Ser confiável é uma das qualidades mais raras — e mais valiosas.",
  "Cumprir o prometido constrói uma reputação que o talento sozinho não constrói.",
  "O comprometimento diário é o que sustenta os grandes resultados.",
  "Seja alguém em quem os outros podem confiar de olhos fechados.",
  "Você é capaz de mais do que imagina no seu pior dia.",
  "A força que você precisa já está dentro de você, só falta usar.",
  "Dias difíceis também ensinam, mesmo doendo.",
  "Você já superou 100% dos seus piores dias até agora.",
  "Confie no processo mesmo quando ele parecer devagar demais.",
  "O cansaço de hoje é prova de que você está se esforçando de verdade.",
  "Continue — o resultado sempre chega pra quem não para.",
  "Seu esforço de hoje ninguém vê, mas o resultado, todo mundo vai notar.",
  "Trabalhar com propósito transforma obrigação em realização.",
  "Antes de julgar o dia difícil, lembre de tudo que você já superou.",
  "A vida profissional também é feita de pequenas alegrias diárias — repare nelas.",
  "Ser gentil com quem está mal-humorado também é um exercício de força.",
  "Seu bom humor pode ser o único momento leve no dia de alguém.",
  "Trate bem quem trata mal — isso fala mais sobre você do que sobre ele.",
  "A paciência com o difícil revela o tamanho do seu profissionalismo.",
  "Nem todo cliente difícil quer ser difícil — às vezes só está tendo um dia ruim.",
  "Compreender antes de reagir evita muitos conflitos desnecessários.",
  "Um sorriso genuíno desarma até o cliente mais impaciente.",
  "O profissionalismo aparece justamente nos momentos mais difíceis.",
  "Você não controla o clima do dia, mas controla o clima que você leva pro trabalho.",
  "Cada detalhe do seu trabalho conta uma história sobre quem você é.",
  "Zele pela sua ferramenta de trabalho como zela pelo seu nome.",
  "Cuidar do ambiente também é cuidar da experiência do cliente.",
  "Organização no trabalho reflete organização na mente.",
  "Um espaço limpo e cuidado já é meio caminho de um bom atendimento.",
  "Detalhes pequenos, como capricho na finalização, fazem toda diferença.",
  "O profissional cuidadoso se destaca sem precisar dizer nada.",
  "Seu ambiente de trabalho é reflexo do respeito que você tem pelo seu ofício.",
  "Toda grande jornada é feita de pequenos dias comuns bem vividos.",
  "Você não precisa ver o caminho todo pra dar o próximo passo certo.",
  "O resultado de um ano se constrói nas escolhas de cada dia dele.",
  "Nem todo dia será extraordinário, mas todo dia pode ser bem vivido.",
  "Escolha, hoje de novo, ser a melhor versão possível de você mesmo.",
  "A qualidade do seu trabalho fala por você antes mesmo de você abrir a boca.",
  "Não é o quanto você trabalha, é o quanto você entrega com atenção.",
  "Cada novo cliente é uma oportunidade de mostrar o seu melhor trabalho.",
  "O profissional que se atualiza sempre está um passo à frente.",
  "Ser referência começa em tratar bem quem ninguém mais notaria.",
  "A excelência não é um destino, é uma prática diária.",
  "Trabalhe hoje pensando no cliente que você quer atender pelos próximos anos.",
  "Seu esforço silencioso de hoje é a base do seu reconhecimento de amanhã.",
  "Ninguém constrói uma boa reputação da noite pro dia — e tudo bem, o tempo é seu aliado.",
  "Escolher fazer certo, mesmo no caminho mais difícil, é o que forma o caráter.",
  "O jeito como você trata os detalhes revela o profissional que você é.",
  "Uma boa conversa pode ser tão importante quanto um bom corte.",
  "Cuide da sua energia — ela é sentida por quem está do seu lado.",
  "O respeito pelo tempo do cliente também é parte do seu serviço.",
  "Você é capaz de recomeçar quantas vezes for preciso.",
  "A confiança que você constrói hoje sustenta os próximos anos da sua carreira.",
  "Faça do seu trabalho um motivo de orgulho, não só de sustento.",
  "Cada dia é uma nova chance de ser um pouco mais você mesmo, no seu melhor.",
  "O que parece pequeno hoje pode ser exatamente o que fará a diferença amanhã.",
];

export function fraseDoDia(data: Date = new Date()): string {
  const inicioDoAno = new Date(data.getFullYear(), 0, 0);
  const diffMs = data.getTime() - inicioDoAno.getTime();
  const diaDoAno = Math.floor(diffMs / (1000 * 60 * 60 * 24));
  const indice = (diaDoAno - 1 + FRASES_DO_DIA.length) % FRASES_DO_DIA.length;
  return FRASES_DO_DIA[indice];
}
