import {
  LayoutDashboard,
  Users,
  Scissors,
  Tag,
  Clock,
  CreditCard,
  Layers,
  Wallet,
  HandCoins,
  TrendingUp,
  Gauge,
  Image,
  Receipt,
  ArrowLeftRight,
  ClipboardList,
  Target,
  Package,
  UserPlus,
  Sparkles,
  Trophy,
  type LucideIcon,
} from "lucide-react";

export const ICONES_NAV: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  gerenteVirtual: Sparkles,
  clientes: Users,
  barbeiros: Scissors,
  servicos: Tag,
  produtos: Package,
  atendimentos: Clock,
  indicacoes: UserPlus,
  ranking: Trophy,
  assinaturas: CreditCard,
  planos: Layers,
  caixa: Wallet,
  contas: Receipt,
  comissoes: HandCoins,
  metas: Target,
  financeiro: TrendingUp,
  fluxoCaixa: ArrowLeftRight,
  dre: ClipboardList,
  eficiencia: Gauge,
  totem: Image,
};
